name: exist2025
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12.7
  - pip
  - numpy
  - pandas
  - matplotlib
  - librosa
  - seaborn
  - flask
  - pip:
      - loguru
      - openai-whisper
      - scikit-learn==1.5.*
      - xgboost==2.1.*
      - transformers
      - torch
      - torchvision
      - torchaudio
      - tqdm
      - sentence-transformers
      - datasets
      - evaluate
      - jiwer
      - accelerate
      - transformers
      - tensorboardX
      - speechbrain
      - opensmile
      - tqdm
      - tiktoken
      - blobfile
      - flask-cors
      - openai
      - python-dotenv
      - espeakng
      - nltk
      - textblob
      - moviepy
      - google-genai
      - PyEvALL
      - dotenv
      - optuna